- name: Create instance(s) | Provision a VM with GitLab runner
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: 12345678901-compute@developer.gserviceaccount.com
    credentials_file: /opt/ansible/inventory/service-account.json
    project_id: ansible-123456
    machine_type: f1-micro
    image: centos-7
