- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
    gcp_cred_kind: serviceaccount

    service_account_email: 954671700559-compute@developer.gserviceaccount.com
    credentials_file: /opt/ansible/inventory/service-account.json
    gcp_project: playground-s-11-361e32bc
    region: "northamerica-northeast1"
    zone: "northamerica-northeast1-a"
    machine_type: e2-medium
    image: centos-7

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 50
         source_image: 'projects/centos-cloud/global/images/family/centos-7'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ credentials_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ credentials_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: gitlab-runner
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ credentials_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
   - name: deploy | Copying deploy-gitlab-runner-script.sh
     copy:
       src: "/opt/ansible/inventory/deploy-gitlab-runner-script.sh"
       dest: "/tmp/deploy-gitlab-runner-script.sh"
       owner: root
       group: root
       mode: 0755
   - shell: "sudo su - ; cd /tmp/ ; sudo sh deploy-gitlab-runner-script.sh"
   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60
   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances


- name: Manage new instances
  hosts: new_instances
  connection: ssh
  become: True