#!/bin/sh
sudo useradd -c ansible -d /home/ansible -s /bin/bash ansible
sudo passwd -d ansible
sudo usermod -aG wheel ansible
sudo su - ansible
sudo yum -y upgrade
sudo yum -y install epel-release > /tmp/1-epel-release.txt
sudo yum -y install git python3 openssl ansible > /tmp/2-git-python-ssl-ansible.txt
sudo yum -y install python-pip > /tmp/3-pip.txt
sudo yum -y install python-devel MySQL-python sshpass libffi-devel openssl-devel > /tmp/4-devel.txt
#sudo pip install --upgrade pip (this is breaking)
sudo pip install requests google-auth
sudo pip install apache-libcloud
sudo mkdir -p /opt/ansible/inventory
sudo chmod -R 755 /opt/ansible
sudo chown -R ansible:ansible /opt/ansible
git clone https://github.com/ansible-collections/community.google.git
sleep 15
sudo cp community.google/scripts/inventory/gce.py /opt/ansible/inventory/
sudo cp community.google/scripts/inventory/gce.ini /opt/ansible/inventory/
sudo chown -R ansible:ansible /opt/ansible/inventory/gce.py
sudo chown -R ansible:ansible /opt/ansible/inventory/gce.ini
git clone https://github.com/maolopez/Deploying-to-GCP-with-Terraform-and-Ansible.git
sudo cp Deploying-to-GCP-with-Terraform-and-Ansible/ansible-vm.yml /opt/ansible/inventory/
sudo cp Deploying-to-GCP-with-Terraform-and-Ansible/deploy-gitlab-runner-script.sh /opt/ansible/inventory/
sudo chown -R ansible:ansible /opt/ansible/inventory/ansible-vm.yml
sudo chown -R ansible:ansible /opt/ansible/inventory/deploy-gitlab-runner-script.sh
ansible --version > /tmp/5-ansible-version.txt
cd /opt/ansible/inventory
python -mjson.tool service-account.json
ansible-inventory --list -i gcp.yaml > gcp.yaml
export GCE_INI_PATH=/opt/ansible/inventory/gce.ini
sudo sed -i '/remote_user = root/s/#//' /etc/ansible/ansible.cfg
sudo sed -i '/\[inventory\]/a inventory = /opt/ansible/inventory/gcp.yaml' /etc/ansible/ansible.cfg
ansible-playbook ansible-vm.yml
#place service-account.json in /opt/ansible/inventory/
